var hierarchy =
[
    [ "samurai::memory::AllocatedBlock", "structsamurai_1_1memory_1_1_allocated_block.html", null ],
    [ "samurai::AssetManagerWindow", "structsamurai_1_1_asset_manager_window.html", null ],
    [ "Block", "struct_block.html", null ],
    [ "samurai::Button", "structsamurai_1_1_button.html", null ],
    [ "Container", "struct_container.html", [
      [ "Gameplay", "struct_gameplay.html", null ],
      [ "Mario", "struct_mario.html", null ],
      [ "MarioEditor", "struct_mario_editor.html", null ]
    ] ],
    [ "samurai::ContainerInformation", "structsamurai_1_1_container_information.html", null ],
    [ "samurai::ContainerManager", "structsamurai_1_1_container_manager.html", null ],
    [ "ContainerStaticInfo", "struct_container_static_info.html", null ],
    [ "samurai::ContainersWindow", "structsamurai_1_1_containers_window.html", null ],
    [ "samurai::Context", "structsamurai_1_1_context.html", null ],
    [ "samurai::memory::CustomAllocator", "structsamurai_1_1memory_1_1_custom_allocator.html", null ],
    [ "samurai::Editor", "structsamurai_1_1_editor.html", null ],
    [ "samurai::memory::FreeBlock", "structsamurai_1_1memory_1_1_free_block.html", null ],
    [ "samurai::samuraiImgui::ImGuiIdsManager", "structsamurai_1_1samurai_imgui_1_1_im_gui_ids_manager.html", null ],
    [ "samurai::Input", "structsamurai_1_1_input.html", null ],
    [ "samurai::LogManager", "structsamurai_1_1_log_manager.html", null ],
    [ "samurai::LogWindow", "structsamurai_1_1_log_window.html", null ],
    [ "Mapping", "struct_mapping.html", null ],
    [ "samurai::memory::MemoryArena", "structsamurai_1_1memory_1_1_memory_arena.html", null ],
    [ "samurai::memory::MemoryBlock", "structsamurai_1_1memory_1_1_memory_block.html", null ],
    [ "samurai::GL::PikaFramebuffer", "structsamurai_1_1_g_l_1_1_pika_framebuffer.html", null ],
    [ "Player", "struct_player.html", null ],
    [ "RequestedContainerInfo", "struct_requested_container_info.html", null ],
    [ "samurai::RuntimeContainer", "structsamurai_1_1_runtime_container.html", null ],
    [ "samurai::ShortcutManager::Shortcut", "structsamurai_1_1_shortcut_manager_1_1_shortcut.html", null ],
    [ "samurai::ShortcutManager", "structsamurai_1_1_shortcut_manager.html", null ],
    [ "samurai::ShortcutsWindow", "structsamurai_1_1_shortcuts_window.html", null ],
    [ "samurai::StaticVector< T, N >", "structsamurai_1_1_static_vector.html", null ],
    [ "samurai::StaticVector< char, N >", "structsamurai_1_1_static_vector.html", [
      [ "samurai::StaticString< 16 >", "structsamurai_1_1_static_string.html", null ],
      [ "samurai::StaticString< N >", "structsamurai_1_1_static_string.html", null ]
    ] ],
    [ "samurai::StaticVector< samurai::memory::CustomAllocator, MaxAllocatorsCount >", "structsamurai_1_1_static_vector.html", null ],
    [ "samurai::StaticVector< samurai::StaticString< 16 >, 16 >", "structsamurai_1_1_static_vector.html", null ],
    [ "samurai::StaticVector< size_t, MaxAllocatorsCount >", "structsamurai_1_1_static_vector.html", null ],
    [ "Transform", "struct_transform.html", null ],
    [ "samurai::Window", "structsamurai_1_1_window.html", null ],
    [ "WindowRect", "struct_window_rect.html", null ],
    [ "samurai::WindowState", "structsamurai_1_1_window_state.html", null ]
];